_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "/home/wanghm/model_final_68b088.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
SOLVER:
  STEPS: (260000, 320000)
  MAX_ITER: 330000
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 10000
OUTPUT_DIR:
  "./weights/oneBranch_CHEX"
DATASETS:
  TRAIN: ("OpenImagesV7_train",)
  TEST: ("OpenImagesV7_train",)